# ============================================================================
# Settings
# ============================================================================

# ---------- General ----------

general:
  owners:
    - DISCORD_ID
    - DISCORD_ID
  developers:
    - DISCORD_ID
    - DISCORD_ID

  dev_guild_ids:
    - GUILD_ID
    - GUILD_ID

  enabled_cogs:
    - bot_management

  disabled_cogs:

  # Used to send a message to a webhook when an error occurs on top of logging it outside of Discord.
  webhook_url: "YOUR_WEBHOOK_URL"

# ---------- Action log ----------

action_log:
  GUILD_ID_1:
    message_events:
      delete:
        enabled: true
        channel_id: CHANNEL_ID
      edit:
        enabled: true
        channel_id: CHANNEL_ID
      bulk_delete:
        enabled: true
        channel_id: CHANNEL_ID

  GUILD_ID_2:
    message_events:
      delete:
        enabled: true
        channel_id:
      edit:
        enabled: true
        channel_id:
      bulk_delete:
        enabled: true
        channel_id:
    member_events:
      join:
        enabled: true
        channel_id:
      leave:
        enabled: true
        channel_id:
      role_add:
        enabled: true
        channel_id:
      role_remove:
        enabled: true
        channel_id:
      timeout:
        enabled: true
        channel_id:
      nickname_change:
        enabled: true
        channel_id:
      ban:
        enabled: true
        channel_id:
      unban:
        enabled: true
        channel_id:

# ---------- Staff Rating ----------

staff_rating:
  "": 
    enabled: true
    auto_post: true 
    channel_id:  
    spreadsheet_url: ""
    mention_role_id:  

  "": 
    enabled: true
    auto_post: false 
    channel_id: 
    spreadsheet_url: ""
    mention_role_id:
